### ISSUE TITLE
 CN-TILE plugin？

### ISSUE THREAD

**Issue by aimarxjg** [ironjr/StreamMultiDiffusion#3]
Is that right?  Why not XL？SD3 is coming soon,  Are you still using SD1.5?！

**Comment by ironjr** [comment]
Thanks for your interest in our project! You have made a very good point. I'm currently working on SDXL, so please wait for more update :)

**Comment by ironjr** [comment]
FYI: And as you have mentioned, CN-Tile plugin is also on my TODO list

**Comment by ironjr** [comment]
We now support SDXL. You can check our new demo [here](https://huggingface.co/spaces/ironjr/SemanticPaletteXL).

Hope you like it :)
